#!/bin/bash
set -o errexit -o pipefail -o xtrace

branch=${1:-master}
cmd="/home/isucon/isucon10-qualify/bin/.x /home/isucon/isucon10-qualify/bin/deploy ${branch}"

if type parallel &>/dev/null; then
  parallel -k "ssh {} ${cmd}" ::: isucon10-qualify-{1..3}
else
  for host in isucon10-qualify-{1..3}; do
    ssh ${host} ${cmd}
  done
fi
